import IMAGE from '../../assets/AllImages.js';

export const events = [
  {
    organizationName: 'The P.E.E.R. Center',
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.shark,
    eventLocation: 'Essex',
    dayOfEvent: '30',
    monthOfEvent: 'JAN',
    eventTime: '4:30PM',
    spotsLeft: '3 SPOTS LEFT',
    eventTitle: 'The P.E.E.R. Center Community Help',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.garden,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Spring Nature Project',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: 'The P.E.E.R. Center',
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.animal,
    eventLocation: 'Essex',
    dayOfEvent: '30',
    monthOfEvent: 'JAN',
    eventTime: '4:30PM',
    spotsLeft: '3 SPOTS LEFT',
    eventTitle: 'Event for Animals',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.art,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Art',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.community,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Community',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.conservation,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Conservation',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.crisis,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Crisis',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.education,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Education',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.energy,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Energy',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.equality,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Equality',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.food,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Food',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.health,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Health',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.homeless,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Homeless',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: 'check-circle',
    imageUri: IMAGE.peace,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Peace',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.poverty,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Poverty',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.refugees,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Refugees',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
  {
    organizationName: "Alzheimer's Association",
    verifiedIcon: '',
    imageUri: IMAGE.religious,
    eventLocation: 'Not Essex?',
    dayOfEvent: '13',
    monthOfEvent: 'MAR',
    eventTime: '10:00AM',
    spotsLeft: '60 SPOTS LEFT',
    eventTitle: 'Event for Religious',
    progressBarProgress: 0.75,
    numberOfSpotsLeft: '3/4 SPOTS LEFT',
    extendedDate: 'Thursday, January 30th 2020',
    frameOfEvent: '4:30 PM - 6:00 PM',
    address: '205 N Hamilton Rd, Essex SS11 1EP',
    whatWillTheyDo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enimad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
    whoCanTheyContact:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    whereShouldTheyGo:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    latitude: 47.191567,
    longitude: -52.837118,
  },
];

export default events;
