# Generated by Django 3.0.3 on 2020-02-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(null=True)),
                ('type', models.CharField(choices=[('NGO', 'Non Governmental Organisation'), ('XX1', 'Option 2'), ('XX2', 'Option 3')], max_length=3, null=True)),
                ('charity_number', models.IntegerField()),
                ('exemption_type', models.CharField(choices=[('1', 'Low income'), ('2', 'Exemption from regulation')], max_length=1, null=True)),
                ('logo', models.URLField()),
            ],
        ),
    ]
