# Generated by Django 3.0.3 on 2020-02-25 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(null=True)),
                ('type', models.CharField(choices=[('NGO', 'Non Governmental Organisation'), ('XX1', 'Option 2'), ('XX2', 'Option 3')], max_length=3, null=True)),
                ('charity_number', models.IntegerField()),
                ('exemption_type', models.CharField(choices=[('1', 'Low income'), ('2', 'Exemption from regulation')], max_length=1, null=True)),
                ('logo', models.URLField()),
                ('charity_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
