repos:
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.2.0
  hooks:
  - id: seed-isort-config
    args:
    - --application-directories=backend
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5  # Use the sha / tag you want to point at
  hooks:
  - id: autopep8
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    types: [python]
  - id: flake8
    name: flake8
    entry: flake8
    language: system
    types: [python]