version: '3'

services:

  backend:
    build: .
    volumes:
      - .:/opt/services/backend/src
      - static_volume:/opt/services/backend/static  # <-- bind the static volume
      - media_volume:/opt/services/backend/media  # <-- bind the media volume
    networks:
      - nginx_network
      - database1_network  # <-- connect to the bridge
    depends_on:  # <-- wait for db to be "ready" before starting the app
      - database1

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/backend/static  # <-- bind the static volume
      - media_volume:/opt/services/backend/media  # <-- bind the media volume
    depends_on:
      - backend
    networks:
      - nginx_network

  database1:  # <-- IMPORTANT: same name as in DATABASES setting, otherwise Django won't find the database!
    image: postgres:11
    env_file:  # <-- we use the previously defined values
      - config/db/database1_env
    networks:  # <-- connect to the bridge
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data

networks:
  nginx_network:
    driver: bridge
  database1_network:  # <-- add the bridge
    driver: bridge

volumes:
  database1_volume:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume