# Generated by Django 3.0.3 on 2020-02-29 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('karmaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprofile',
            name='activation_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='activation_token_valid_until',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='charity_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='exemption',
            field=models.CharField(blank=True, choices=[('1', 'Non-government organisation'), ('2', 'Other type'),
                                                        ('3', 'Other type 2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='is_activated',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='magic_link_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='magic_link_token_valid_until',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='password_reset_token_valid_until',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='terms_consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='terms_consent_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Non-government organisation'), ('2', 'Other type'),
                                                        ('3', 'Other type 2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_charity',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activation_token_valid_until',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_activated',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='magic_link_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='magic_link_token_valid_until',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_token_valid_until',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='terms_consent_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
