# Generated by Django 3.0.3 on 2020-02-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('karmaapp', '0002_make_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_charity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
