# Generated by Django 3.0.3 on 2020-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0002_create_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
