# Generated by Django 3.0.3 on 2020-04-20 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0002_name_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityprofile',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='activation_token_valid_until',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='password_reset_token_valid_until',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='terms_consent',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='terms_consent_datetime',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_token_valid_until',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_activated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_reset_token_valid_until',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='terms_consent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='terms_consent_datetime',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_token_valid_until',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_valid_until',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_consent_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
