# Generated by Django 3.0.3 on 2020-02-29 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0002_alter_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField()),
                ('type', models.CharField(choices=[('1', 'Non-government organisation'), ('2', 'Other type'), ('3', 'Other type 2')], max_length=1, null=True)),
                ('charity_number', models.IntegerField()),
                ('exemption', models.CharField(choices=[('1', 'Non-government organisation'), ('2', 'Other type'), ('3', 'Other type 2')], max_length=1, null=True)),
                ('logo', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
