# Generated by Django 3.0.3 on 2020-04-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0003_simplify_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='charity',
            field=models.ManyToManyField(null=True, to='karmaapp.CharityProfile'),
        ),
    ]
