# Generated by Django 3.0.3 on 2020-03-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('karmaapp', '0003_is_charity_false_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('number_spots', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('age_check', models.BooleanField(blank=True, default=True, null=True)),
                ('photo_check', models.BooleanField(blank=True, default=False, null=True)),
                ('physical_activity_check', models.BooleanField(blank=True, default=False, null=True)),
                ('additional_info_check', models.BooleanField(blank=True, default=False, null=True)),
                ('causes_type', models.ManyToManyField(to='karmaapp.Cause')),
                ('charity', models.ManyToManyField(to='karmaapp.CharityProfile')),
            ],
        ),
        migrations.AddField(
            model_name='charityprofile',
            name='causes',
            field=models.ManyToManyField(to='karmaapp.Cause'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='causes',
            field=models.ManyToManyField(to='karmaapp.Cause'),
        ),
    ]
