# Generated by Django 3.0.3 on 2020-02-25 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karmaapp', '0003_userprofile_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='genre',
            new_name='gender',
        ),
    ]
